version: "3.7"
services:
  mysqldb:
    image: mysql:8.0.1
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    container_name: mysql-apirest
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysqldb
    depends_on:
      - mysqldb
    container_name: phpmyadmin-apirest
  
  backend:
    depends_on:
      - mysqldb
    image: sunfan12/apirest-producer:v0.0.2
    build:
      context: ./PrimerAPIRest
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?useSSL=false",
        "spring.datasource.username" : "${MYSQLDB_USER}",
        "spring.datasource.password" : "${MYSQLDB_ROOT_PASSWORD}",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update" }'
    container_name: producer-apirest

  frontend:
    depends_on:
      - backend
    image: sunfan12/apirest-consumer:v0.0.2
    build:
      context: ./UserCrudInvocandoRest_SpringBoot2
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT_CLIENT}:${SPRING_DOCKER_PORT_CLIENT}
    environment:
      SPRING_APPLICATION_JSON: '{
          "service.persona.url"  : "${SPRING_CLIENT_SERVICE_URL}"
          }'
    container_name: consumer-apirest

volumes:
  mysql-data:

